version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_ilabs
    restart: always
    environment:
      POSTGRES_DB=labs_db
      POSTGRES_USER=root
      POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin 

volumes:
  postgres_data:
  pgadmin_data: