name: Linting and Formatting

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    name: Lint and Format Codebase
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up npm
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Lint frontend
      working-directory: ./frontend
      run: npm run lint

    - name: Format frontend
      working-directory: ./frontend
      run: npm run format

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint backend
      working-directory: ./backend
      run: pylint --disable=C0303 **/*.py